### ISSUE TITLE
使用shamrock时随机功能会出现错误

### ISSUE THREAD

**Issue by F1Justin** [jcjrobert/nonebot-plugin-random#12]
日志：
11-11 23:43:30 [SUCCESS] nonebot | OneBot V11 985393579 | [message.group.normal]: Message 1998120617 from **********@[群:*********] '随机飞舞'
11-11 23:43:30 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_repeater)
11-11 23:43:30 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_repeater) running complete
11-11 23:43:30 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot-plugin-random.matchers)
11-11 23:43:30 [INFO] nonebot | Matcher(type='message', module=nonebot-plugin-random.matchers) running complete
11-11 23:43:30 [ERROR] nonebot | Running Matcher(type='message', module=nonebot-plugin-random.matchers) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot/__init__.py", line 333, in run
    get_driver().run(*args, **kwargs)
  File "/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 199, in run
    uvicorn.run(
  File "/Users/justin/lily/.venv/lib/python3.9/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/Users/justin/lily/.venv/lib/python3.9/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Users/justin/miniconda3/envs/bot/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot/message.py", line 467, in check_and_run_matcher
    await _run_matcher(
> File "/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot/message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 759, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 734, in simple_run
    await handler(
  File "/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot-plugin-random/matchers.py", line 103, in handle
    await bot_send(
  File "/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot-plugin-random/matchers.py", line 42, in bot_send
    await bot.send(
  File "/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot_plugin_guild_patch/__init__.py", line 30, in patched_send
    return await original_send(self, event, message, **kwargs)
  File "/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot/adapters/onebot/v11/bot.py", line 220, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot/adapters/onebot/v11/bot.py", line 174, in send
    return await bot.send_msg(**params)
  File "/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot/internal/adapter/bot.py", line 120, in call_api
    raise exception
  File "/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot/internal/adapter/bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 140, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "/Users/justin/lily/.venv/lib/python3.9/site-packages/nonebot/adapters/onebot/v11/utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=35000, data={}, message='消息合成失败，请查看日志或者检查输入。', echo='2')

**Comment by jcjrobert** [comment]
更新了，你看看还会不会报错

**Comment by F1Justin** [comment]
失踪人口回归！可惜已经不用shamrock因此无法测试了（
